### ISSUE TITLE
Bug on vote_by_hash kaitai specification

### ISSUE THREAD

**Issue by marcosmmb** [nanocurrency/protocol#28]
Currently, this is the kaitai specification for `vote_by_hash`:

```yaml
  vote_by_hash:
    doc: A sequence of hashes, where count is read from header.
    seq:
      - id: hashes
        size: 32
        repeat: until
        repeat-until: _index == _root.header.item_count_int or _io.eof
        if: not _io.eof
```

which generates the following Python code upon compilation:

```python
    class VoteByHash(KaitaiStruct):
        """A sequence of hashes, where count is read from header."""
        def __init__(self, _io, _parent=None, _root=None):
            self._io = _io
            self._parent = _parent
            self._root = _root if _root else self
            self._read()

        def _read(self):
            if not (self._io.is_eof()):
                self.hashes = []
                i = 0
                while True:
                    _ = self._io.read_bytes(32)
                    self.hashes.append(_)
                    if  ((i == self._root.header.item_count_int) or (self._io.is_eof())) :
                        break
                    i += 1
```

Notice that the hash list `self.hashes` will end up with a size of `item_count_int + 1`, which will "leak" and consider the first 32 bytes of the next byte string as a block hash, while it is usually the start of a new message.

From my tests, it seems that updating the line to
```yaml
repeat-until: _index == (_root.header.item_count_int - 1) or _io.eof
```
will fix the issue.
